# Study05 is a frozen design and generator, not an evaluation runner.
# No reserved evaluation measurements are generated by sourcing this file.
study05_settings <- function() {
  list(B = 199L, data_seed = 261003L, bootstrap_seed_base = 5400000L,
       targets = c("E015", "E003", "E006"), min_valid = 20L,
       min_success = .95, level = .95, cov_tol = 1e-8,
       engine_version = "0.0.7.9000", sigma = .25, rho_time = .6,
       gaps = c(1, .1, .01), contamination = c(0, .25, .5),
       contaminated_ids = c("E002", "E004", "E008"),
       contamination_direction = c(.6, -.8, 0),
       fixture_seed = 779L, fixture_dataset = 999L,
       evaluation_stage = "reserved_robustness_evaluation",
       fixture_stage = "reserved_engineering_fixture")
}

study05_cases <- function() {
  s <- study05_settings(); rows <- list()
  add <- function(g, a, m, motion, rho, M, role) {
    label <- function(x) gsub("\\.", "p", format(x, scientific = FALSE, trim = TRUE))
    rows[[length(rows) + 1L]] <<- data.frame(
      case_id = paste0(if (rho > 0) "ar1" else if (motion) "movement" else "main",
                       "_g", label(g), "_a", label(a), "_m", m),
      scenario = "gapped_gaussian", g = g, signal_gap_fraction = g, a = a, m = as.integer(m),
      M = as.integer(M), B = s$B, focal_motion = motion,
      movement_scale = if (motion) .2 else 0, rho_unit = rho,
      role = role, target_regime = if (motion) "focal_movement" else if (a > 0)
        "anchor_change" else "null", contract = if (rho > 0) "dependence_stress_outside_iid_contract" else
        "iid_units_nominal_contract", stringsAsFactors = FALSE)
  }
  for (g in s$gaps) for (a in s$contamination) for (m in c(40L, 160L))
    add(g, a, m, FALSE, 0, 60L, if (a == 0) "null_reference" else "anchor_change")
  for (g in c(1, .01)) for (a in c(0, .5)) for (m in c(40L, 160L))
    add(g, a, m, TRUE, 0, 40L, "movement_control")
  for (g in c(1, .01)) for (m in c(40L, 160L))
    add(g, 0, m, FALSE, .5, 40L, "dependence_stress")
  rows[[length(rows) + 1L]] <- data.frame(case_id = "legacy_rare_axis_m12",
    scenario = "rare_axis", g = NA_real_, signal_gap_fraction = NA_real_, a = 0, m = 12L, M = 80L, B = s$B,
    focal_motion = TRUE, movement_scale = .2, rho_unit = 0,
    role = "sparse_unit_control", target_regime = "focal_movement", contract = "iid_units_nominal_contract",
    stringsAsFactors = FALSE)
  result <- do.call(rbind, rows); result$case_index <- seq_len(nrow(result))
  rownames(result) <- NULL
  result
}

study05_validate_case <- function(case, boundary_fixture = FALSE, fixture = FALSE) {
  required <- names(study05_cases())
  if (!is.data.frame(case) || nrow(case) != 1L || !all(required %in% names(case)))
    stop("Supply one complete study05 case row.", call. = FALSE)
  planned <- study05_cases()
  row <- match(case$case_index, planned$case_index)
  if (is.na(row)) stop("Unknown case index.", call. = FALSE)
  expected <- planned[row, , drop = FALSE]
  if (isTRUE(boundary_fixture)) {
    if (case$scenario != "gapped_gaussian" || !identical(as.numeric(case$g), 0))
      stop("A boundary fixture must be a Gaussian case with g=0.", call. = FALSE)
    expected$g <- expected$signal_gap_fraction <- 0
  }
  if (isTRUE(fixture)) {
    if (!is.numeric(case$B) || length(case$B) != 1L || !is.finite(case$B) ||
        case$B < 1L || case$B > study05_settings()$B || case$B != floor(case$B))
      stop("Fixture B must be an integer from 1 through 199.", call. = FALSE)
    expected$B <- case$B
  }
  same <- vapply(required, function(nm) isTRUE(all.equal(case[[nm]], expected[[nm]],
    check.attributes = FALSE, tolerance = 0)), logical(1L))
  if (!all(same)) stop("Case differs from frozen design: ",
                      paste(required[!same], collapse = ", "), ".", call. = FALSE)
  invisible(case)
}

study05_preserve_rng <- function(code) {
  old_kind <- RNGkind()
  had_seed <- exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)
  if (had_seed) old_seed <- get(".Random.seed", envir = .GlobalEnv)
  on.exit({
    do.call(RNGkind, as.list(old_kind))
    if (had_seed) assign(".Random.seed", old_seed, envir = .GlobalEnv) else
      if (exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE))
        rm(".Random.seed", envir = .GlobalEnv)
  }, add = TRUE)
  force(code)
}

study05_seed_state <- function(seed) study05_preserve_rng({
  RNGkind("L'Ecuyer-CMRG", "Inversion", "Rejection")
  set.seed(seed)
  get(".Random.seed", envir = .GlobalEnv)
})

study05_jobs <- function(cases = study05_cases()) {
  if (!is.data.frame(cases) || nrow(cases) < 1L ||
      !"case_index" %in% names(cases) || anyDuplicated(cases$case_index))
    stop("Cases must be a nonempty data frame with unique case indices.", call. = FALSE)
  for (k in seq_len(nrow(cases))) study05_validate_case(cases[k, , drop = FALSE])
  # All streams retain their positions in the complete case-major design even
  # when a caller requests a subset of cases. No normal variates are drawn.
  s <- study05_settings(); planned <- study05_cases()
  stream <- study05_seed_state(s$data_seed); jobs <- list()
  for (k in seq_len(nrow(planned))) for (i in seq_len(planned$M[k])) {
    if (planned$case_index[k] %in% cases$case_index)
      jobs[[length(jobs) + 1L]] <- list(case_id = planned$case_id[k],
        case_index = planned$case_index[k], dataset_id = as.integer(i),
        m = planned$m[k], data_stream = stream,
        bootstrap_seed = as.integer(s$bootstrap_seed_base + 10000L * k + i),
        stage = s$evaluation_stage)
    stream <- parallel::nextRNGStream(stream)
  }
  jobs
}

study05_ar1_units <- function(innovations, rho) {
  if (!is.matrix(innovations) || !is.numeric(innovations) ||
      any(!is.finite(innovations)) || ncol(innovations) < 1L || nrow(innovations) < 1L ||
      !is.numeric(rho) || length(rho) != 1L || !is.finite(rho) || abs(rho) >= 1)
    stop("AR(1) requires a finite nonempty innovation matrix and |rho|<1.", call. = FALSE)
  result <- innovations
  if (ncol(result) > 1L) for (j in 2:ncol(result))
    result[, j] <- rho * result[, j - 1L] + sqrt(1 - rho^2) * innovations[, j]
  result
}

study05_anchor_diagnostics <- function(points, declared, clean) {
  rows <- list()
  for (name in c("declared", "clean")) {
    idx <- if (name == "declared") declared else clean
    centered <- lapply(points, function(z) sweep(z[idx, , drop = FALSE], 2L,
                                               colMeans(z[idx, , drop = FALSE]), "-"))
    for (period in 1:2) {
      d <- svd(centered[[period]], nu = 0L, nv = 0L)$d
      rows[[length(rows) + 1L]] <- data.frame(anchor_set = name, period = period,
        n_anchors = length(idx), singular_1 = d[1L], singular_2 = d[2L],
        singular_ratio = d[2L] / d[1L], rank = sum(d > 1e-10 * d[1L]),
        condition = d[1L] / d[2L], stringsAsFactors = FALSE)
    }
  }
  do.call(rbind, rows)
}

study05_anchor_registration_diagnostics <- function(points, declared, clean) {
  rows <- lapply(c("declared", "clean"), function(name) {
    idx <- if (name == "declared") declared else clean
    centered <- lapply(points, function(z) sweep(z[idx, , drop = FALSE], 2L,
                                               colMeans(z[idx, , drop = FALSE]), "-"))
    d <- svd(crossprod(centered[[2L]], centered[[1L]]), nu = 0L, nv = 0L)$d
    data.frame(anchor_set = name, n_anchors = length(idx),
      cross_singular_1 = d[1L], cross_singular_2 = d[2L],
      cross_singular_ratio = d[2L] / d[1L],
      cross_rank = sum(d > 1e-10 * d[1L]),
      cross_condition = d[1L] / d[2L], stringsAsFactors = FALSE)
  })
  do.call(rbind, rows)
}

study05_model <- function(case, boundary_fixture = FALSE, fixture = FALSE) {
  study05_validate_case(case, boundary_fixture = boundary_fixture, fixture = fixture)
  s <- study05_settings()
  if (case$scenario == "rare_axis") {
    result <- study03_model(case)
    result$clean_anchor_ids <- setdiff(result$layout$anchors, s$contaminated_ids)
    result$clean_anchors <- match(result$clean_anchor_ids, result$ids)
    result$population_fit_clean <- study03_fit(result$population_grams[[1L]],
      result$population_grams[[2L]], result$population_points[[1L]], result$clean_anchors)
    result$truth_clean <- result$population_fit_clean$displacement[result$target_rows, , drop = FALSE]
    result$truth_declared_minus_clean <- result$truth - result$truth_clean
    result$population_target_identified <- TRUE
    result$population_target_status <- "identified"
    result$baseline_signal_eigenvalues <- NA_real_
    result$contamination_rms <- NA_real_
  } else {
    scenario <- calibration_scenarios()[1L, , drop = FALSE]
    scenario$m <- case$m; scenario$rho_unit <- case$rho_unit
    base <- calibration_layout(scenario)
    scenario$scenario <- "gapped_gaussian"
    scenario$motion <- case$focal_motion
    ids <- rownames(base$latent[[1L]]); n <- length(ids)
    H <- diag(n) - matrix(1 / n, n, n); dimnames(H) <- list(ids, ids)
    original <- H %*% base$latent[[1L]]
    eig <- svd(original, nu = 2L, nv = 0L)
    basis <- cbind(rep(1 / sqrt(n), n), eig$u[, 1:2, drop = FALSE])
    k <- seq_len(n)
    auxiliary <- sin(k * sqrt(2)) + cos(k * sqrt(3))
    u3 <- as.numeric(auxiliary - basis %*% crossprod(basis, auxiliary))
    u3 <- u3 / sqrt(sum(u3^2))
    if (u3[which.max(abs(u3))] < 0) u3 <- -u3
    signal_eigenvalues <- eig$d^2
    first <- cbind(original, z = u3 * sqrt((1 - case$g) * signal_eigenvalues[2L]))
    second <- first
    if (case$focal_motion) {
      second["E006", ] <- second["E006", ] + c(.09, -.06, 0)
      second[13:18, ] <- sweep(second[13:18, , drop = FALSE], 2L, c(-.11, .08, 0), "+")
    }
    rms <- sqrt(mean(rowSums(original^2)))
    if (case$a > 0) second[s$contaminated_ids, ] <- sweep(
      second[s$contaminated_ids, , drop = FALSE], 2L,
      case$a * rms * s$contamination_direction, "+")
    latent <- lapply(list(first, second), function(z) H %*% z)
    layout <- base; layout$latent <- latent
    if (case$focal_motion) {
      layout$entitygroups$movement_group[6L] <- "individual_mover"
      layout$entitygroups$movement_group[13:18] <- "moving_cluster"
    }
    layout$entitygroups$anchor_contaminated <- ids %in% s$contaminated_ids & case$a > 0
    anchors <- match(layout$anchors, ids)
    clean_ids <- setdiff(layout$anchors, s$contaminated_ids)
    clean <- match(clean_ids, ids)
    C <- lapply(latent, function(z) tcrossprod(z) + s$sigma^2 * H)
    target_rows <- match(s$targets, ids)
    values <- lapply(C, function(z) eigen(z, symmetric = TRUE, only.values = TRUE)$values)
    identified <- all(vapply(values, function(v) v[2L] - v[3L] > 1e-10 * v[1L], logical(1L)))
    if (identified) {
      points <- lapply(C, study02_points)
      fit <- study03_fit(C[[1L]], C[[2L]], points[[1L]], anchors)
      fit_clean <- study03_fit(C[[1L]], C[[2L]], points[[1L]], clean)
      truth <- fit$displacement[target_rows, , drop = FALSE]
      truth_clean <- fit_clean$displacement[target_rows, , drop = FALSE]
    } else {
      if (!isTRUE(boundary_fixture)) stop("A planned population plane is unidentified.", call. = FALSE)
      points <- fit <- fit_clean <- NULL
      truth <- matrix(NA_real_, length(target_rows), 2L, dimnames = list(s$targets, c("x", "y")))
      truth_clean <- truth
    }
    result <- list(case = case, scenario = scenario, layout = layout, ids = ids, H = H,
      population_grams = C, population_points = points, population_fit = fit,
      population_fit_clean = fit_clean, anchors = anchors,
      clean_anchor_ids = clean_ids, clean_anchors = clean, target_ids = s$targets,
      target_rows = target_rows, truth = truth, truth_clean = truth_clean,
      truth_declared_minus_clean = truth - truth_clean,
      population_target_identified = identified,
      population_target_status = if (identified) "identified" else "boundary_plane_unidentified",
      baseline_signal_eigenvalues = signal_eigenvalues, auxiliary_direction = u3,
      original_rank2_layout = original, contamination_rms = rms)
  }
  result$contract <- case$contract
  result$population_eigenvalues <- lapply(result$population_grams, function(C)
    eigen(C, symmetric = TRUE, only.values = TRUE)$values)
  result$population_gaps <- do.call(rbind, lapply(1:2, function(t) {
    v <- result$population_eigenvalues[[t]]
    data.frame(period = t, lambda1 = v[1L], lambda2 = v[2L], lambda3 = v[3L],
      boundary_gap = v[2L] - v[3L], relative_gap_lambda1 = (v[2L] - v[3L]) / v[1L],
      relative_gap_lambda2 = (v[2L] - v[3L]) / v[2L])
  }))
  result$anchor_diagnostics <- if (result$population_target_identified)
    study05_anchor_diagnostics(result$population_points, result$anchors, result$clean_anchors) else NULL
  result$anchor_registration_diagnostics <- if (result$population_target_identified)
    study05_anchor_registration_diagnostics(result$population_points, result$anchors,
                                            result$clean_anchors) else NULL
  result
}

study05_validate_job <- function(job, case, allow_evaluation = FALSE) {
  s <- study05_settings()
  if (!is.list(job) || !all(c("case_id", "case_index", "dataset_id", "m",
      "data_stream", "bootstrap_seed", "stage") %in% names(job)))
    stop("Supply a complete study05 job.", call. = FALSE)
  if (!is.integer(job$data_stream) || length(job$data_stream) != 7L ||
      anyNA(job$data_stream) || job$data_stream[1L] != 10407L)
    stop("Job requires an Inversion/Rejection L'Ecuyer-CMRG stream.", call. = FALSE)
  if (!identical(job$case_id, case$case_id) || job$case_index != case$case_index ||
      job$m != case$m) stop("Job and case identifiers or unit count disagree.", call. = FALSE)
  if (identical(job$stage, s$fixture_stage)) {
    study05_validate_case(case, fixture = TRUE)
    if (!identical(job$dataset_id, s$fixture_dataset) ||
        !identical(job$bootstrap_seed, s$fixture_seed) ||
        !identical(job$data_stream, study05_seed_state(s$fixture_seed)))
      stop("Engineering generation is restricted to the exact fixture stream and dataset.", call. = FALSE)
  } else if (identical(job$stage, s$evaluation_stage)) {
    if (!isTRUE(allow_evaluation))
      stop("Reserved evaluation measurements are locked; an explicit later allow_evaluation=TRUE is required.", call. = FALSE)
    study05_validate_case(case)
    if (!is.integer(job$dataset_id) || length(job$dataset_id) != 1L ||
        is.na(job$dataset_id) || job$dataset_id < 1L || job$dataset_id > case$M)
      stop("Reserved dataset ID is invalid.", call. = FALSE)
    expected <- study05_jobs(case)[[job$dataset_id]]
    if (!identical(job, expected)) stop("Reserved job differs from its frozen stream manifest.", call. = FALSE)
  } else stop("Unknown generation stage.", call. = FALSE)
  invisible(job)
}

study05_generate <- function(job, case, allow_evaluation = FALSE) {
  study05_validate_job(job, case, allow_evaluation = allow_evaluation)
  is_fixture <- identical(job$stage, study05_settings()$fixture_stage)
  model <- study05_model(case, fixture = is_fixture)
  if (case$scenario == "rare_axis") {
    answer <- study03_generate(job, case)
    answer$model <- model
    answer$contract <- model$contract
    return(answer)
  }
  study05_preserve_rng({
    assign(".Random.seed", job$data_stream, envir = .GlobalEnv)
    n <- length(model$ids); m <- case$m; s <- study05_settings()
    innovation <- list(loadings = matrix(stats::rnorm(3L * m), 3L, m),
      noise_first = matrix(stats::rnorm(n * m), n, m),
      noise_second = matrix(stats::rnorm(n * m), n, m))
    loadings <- study05_ar1_units(innovation$loadings, case$rho_unit)
    noise_first <- study05_ar1_units(innovation$noise_first, case$rho_unit)
    noise_second <- s$rho_time * noise_first + sqrt(1 - s$rho_time^2) *
      study05_ar1_units(innovation$noise_second, case$rho_unit)
    noise <- list(noise_first, noise_second)
    features <- sprintf("f%03d", seq_len(m))
    X <- lapply(1:2, function(t) {
      z <- model$H %*% (model$layout$latent[[t]] %*% loadings + s$sigma * noise[[t]])
      dimnames(z) <- list(model$ids, features); z
    })
    panel <- do.call(rbind, lapply(1:2, function(t)
      data.frame(entity = model$ids, time = t, X[[t]], check.names = FALSE,
                 stringsAsFactors = FALSE)))
    rownames(panel) <- NULL
    list(data = panel, features = features,
      unit_map = stats::setNames(sprintf("unit%03d", seq_len(m)), features),
      rare = stats::setNames(rep(FALSE, m), features), rare_count = NA_integer_,
      layout = model$layout, model = model, X = X, loadings = loadings,
      noise = noise, innovations = innovation, contract = model$contract)
  })
}

study05_fixture <- function(case_index = 1L, B = 21L, generate = TRUE) {
  if (!is.numeric(case_index) || length(case_index) != 1L || !is.finite(case_index) ||
      case_index != floor(case_index) || !case_index %in% study05_cases()$case_index)
    stop("Fixture case index is invalid.", call. = FALSE)
  if (!is.logical(generate) || length(generate) != 1L || is.na(generate))
    stop("generate must be TRUE or FALSE.", call. = FALSE)
  s <- study05_settings(); case <- study05_cases()[case_index, , drop = FALSE]
  case$B <- B; study05_validate_case(case, fixture = TRUE)
  job <- list(case_id = case$case_id, case_index = case$case_index,
    dataset_id = s$fixture_dataset, m = case$m, data_stream = study05_seed_state(s$fixture_seed),
    bootstrap_seed = s$fixture_seed, stage = s$fixture_stage)
  result <- list(job = job, case = case)
  if (generate) result$generated <- study05_generate(job, case)
  result
}
