args <- commandArgs(trailingOnly = TRUE)
root <- normalizePath(args[[1]], winslash = "/")
.libPaths(c(file.path(root, "qa", "R-library"), .libPaths()))
cat("Verification of recovered package; not a frozen scientific run\n")
print(sessionInfo())
files <- list.files(file.path(root, "driftmapR"), "\\.[Rr]$", recursive = TRUE, full.names = TRUE)
for (f in files) parse(f)
cat("Parsed", length(files), "R files\n")
res <- testthat::test_local(file.path(root, "driftmapR"), reporter = "summary", stop_on_failure = TRUE)
saveRDS(res, file.path(root, "qa", "fresh-test-results.rds"))
tab <- as.data.frame(res)
tab <- tab[, !vapply(tab, is.list, logical(1)), drop = FALSE]
write.csv(tab, file.path(root, "qa", "fresh-test-results.csv"), row.names = FALSE)
cat("Tests completed successfully\n")
