# Only reserved development seed 777 / dataset 999 is used here. No held-out
# calibration job stream or fresh evaluation result is generated by tests.
if (!exists("study03_one", mode = "function") ||
    !exists("study03_validate_result", mode = "function")) {
  roots <- c(".", "..", "data-raw/calibration-03", "driftmapR/data-raw/calibration-03")
  roots <- roots[file.exists(file.path(roots, "run.R")) &
                   file.exists(file.path(roots, "validate.R"))]
  if (!length(roots)) stop("Cannot locate study03 runner and validator.")
  root <- normalizePath(roots[1L])
  source(file.path(root, "run.R"), local = TRUE)
  study03_load(root)
  source(file.path(root, "validate.R"), local = TRUE)
}

study03_reserved_fixture <- function(scenario = "regular_movement", m = 8L) {
  case <- study03_cases()[match(scenario, study03_cases()$scenario), , drop = FALSE]
  case$m <- as.integer(m)
  RNGkind("L'Ecuyer-CMRG", "Inversion", "Rejection")
  set.seed(777L)
  job <- list(case_id = case$case_id, case_index = case$case_index,
              dataset_id = 999L, m = as.integer(m), data_stream = .Random.seed,
              bootstrap_seed = 777L, stage = "reserved_development_fixture")
  list(job = job, case = case, generated = study03_generate(job, case))
}

testthat::test_that("runner is reproducible and extends the same planned prefix", {
  fixture <- study03_reserved_fixture()
  run <- function(B) study03_one(fixture$job, fixture$case, B = B,
                                 generated = fixture$generated, keep_inner_values = TRUE)
  first <- run(21L); second <- run(21L); extended <- run(23L)
  for (name in c("weights", "streams", "point", "estimate", "observed_jackknife",
                  "values", "eval_values", "inner", "pivots", "attempts", "studentization",
                  "regions", "estimates")) {
    testthat::expect_identical(first[[name]], second[[name]])
  }
  testthat::expect_identical(first$weights, extended$weights[1:21, , drop = FALSE])
  testthat::expect_identical(first$streams, extended$streams[1:21, , drop = FALSE])
  testthat::expect_equal(first$values, extended$values[1:21, , , drop = FALSE], tolerance = 0)
  testthat::expect_equal(first$pivots, extended$pivots[1:21, , drop = FALSE], tolerance = 0)
  check <- study03_validate_result(first)
  testthat::expect_identical(check$status, "passed")
  testthat::expect_equal(check$pivot_rows_checked, 21L * 3L)
  testthat::expect_equal(check$retained_jackknives, 22L)
  testthat::expect_gt(check$expanded_occurrence_vectors_reconstructed, 0)
  # Saved identities are actually audited, not merely counted.
  bad <- first; bad$weights[1L, 1L] <- bad$weights[1L, 1L] + 1L
  testthat::expect_error(study03_validate_result(bad), "multiplicity totals")
  bad <- first; bad$pivots[1L, 1L] <- bad$pivots[1L, 1L] + 1
  testthat::expect_error(study03_validate_result(bad), "independent pivot")
  bad <- first; bad$regions$area[1L] <- bad$regions$area[1L] + 1
  testthat::expect_error(study03_validate_result(bad), "region table reconstruction")
})

testthat::test_that("failed required deletions invalidate the whole jackknife without replacement", {
  fixture <- study03_reserved_fixture()
  injected <- function(X, counts, reference_points, anchors, target_rows,
                        grams = NULL, fit_fun = study03_fit) {
    positive <- which(counts > 0L)
    repeated <- which(counts > 1L)
    fail_unit <- if (length(repeated)) repeated[1L] else positive[1L]
    fail_call <- match(fail_unit, positive); calls <- 0L
    fit <- function(...) {
      calls <<- calls + 1L
      if (calls == fail_call) stop("Reserved injected deletion failure.")
      fit_fun(...)
    }
    study03_jackknife(X, counts, reference_points, anchors, target_rows,
                      grams = grams, fit_fun = fit)
  }
  result <- study03_one(fixture$job, fixture$case, B = 21L,
                         generated = fixture$generated, keep_inner_values = TRUE,
                         jackknife_fun = injected)
  testthat::expect_true(result$observed_success)
  testthat::expect_true(all(result$attempts$success))
  testthat::expect_false(any(result$observed_jackknife$covariance_ok))
  testthat::expect_false(any(result$studentization$covariance_ok | result$studentization$pivot_ok))
  testthat::expect_true(all(is.na(result$pivots)))
  testthat::expect_equal(nrow(result$attempts), 21L)
  for (jk in result$inner) {
    failed <- jk$ledger$attempted & !jk$ledger$success
    testthat::expect_equal(sum(failed), 1L)
    testthat::expect_equal(jk$n_successful_occurrences,
                          sum(jk$counts) - sum(jk$counts[failed]))
    testthat::expect_true(all(vapply(jk$covariance, function(S) all(is.na(S)), logical(1))))
  }
  testthat::expect_true(any(vapply(result$inner, function(jk)
    any(jk$ledger$multiplicity[!jk$ledger$success & jk$ledger$attempted] > 1L), logical(1))))
  testthat::expect_false(any(result$regions$delivered[grepl("^jackknife_", result$regions$method)]))
  testthat::expect_identical(study03_validate_result(result)$status, "passed")
  accounting <- study03_deletion_accounting(result)
  testthat::expect_equal(accounting$summary$failed_unique[accounting$summary$phase == "inner"], 21L)
  testthat::expect_equal(nrow(accounting$events), 22L)
  testthat::expect_equal(sum(accounting$events$multiplicity), sum(accounting$summary$failed_occurrences))
})

testthat::test_that("observed-fit failure retains every planned unattempted record", {
  fixture <- study03_reserved_fixture("regular_null")
  result <- study03_one(fixture$job, fixture$case, B = 21L,
                         generated = fixture$generated, keep_inner_values = TRUE,
                         fit_fun = function(...) stop("Reserved observed-fit failure."))
  testthat::expect_false(result$observed_success)
  testthat::expect_equal(nrow(result$attempts), 21L)
  testthat::expect_equal(nrow(result$studentization), 63L)
  testthat::expect_equal(nrow(result$regions), 15L)
  testthat::expect_true(all(rowSums(result$weights) == fixture$job$m))
  testthat::expect_false(any(result$attempts$attempted | result$attempts$success))
  testthat::expect_false(any(result$studentization$pivot_ok))
  testthat::expect_false(any(result$regions$available | result$regions$delivered))
  testthat::expect_true(all(result$regions$reason == "observed_unavailable"))
  testthat::expect_equal(result$outer$n_full_attempted, 0L)
  testthat::expect_equal(result$outer$inner_jackknife_attempted, 0L)
  testthat::expect_gt(result$outer$inner_jackknife_required, 0L)
  testthat::expect_identical(study03_validate_result(result)$status, "passed")
})

testthat::test_that("nonnull truth is the population full estimator in the fixed chart", {
  fixture <- study03_reserved_fixture()
  g <- fixture$generated; model <- g$model
  baseline <- study02_points(tcrossprod(g$X[[1L]]) / fixture$job$m)
  direct <- study03_fit(model$population_grams[[1L]], model$population_grams[[2L]],
                        baseline, model$anchors)
  to_population <- study02_register(baseline, model$population_points[[1L]], model$anchors)
  to_observed <- study02_register(model$population_points[[1L]], baseline, model$anchors)
  testthat::expect_equal(to_observed$rotation %*% to_population$rotation, diag(2L),
                        tolerance = 1e-12)
  testthat::expect_equal(unname(direct$displacement[model$target_rows, , drop = FALSE] %*%
                          to_population$rotation), unname(model$truth), tolerance = 1e-12)
  testthat::expect_gt(sqrt(sum(model$truth[1L, ]^2)), 0.01)
  # Align the noiseless latent geometry as a separate control; its displacement
  # differs from the noise-inflated population embedding target.
  latent1 <- model$H %*% model$layout$latent[[1L]]
  latent2 <- model$H %*% model$layout$latent[[2L]]
  latent_alignment <- study02_register(latent2, latent1, model$anchors)
  latent_to_population <- study02_register(latent1, model$population_points[[1L]], model$anchors)
  latent_displacement <- (latent_alignment$points - latent1) %*% latent_to_population$rotation
  testthat::expect_gt(max(abs(latent_displacement[model$target_rows, ] - model$truth)), 1e-6)
  null <- study03_reserved_fixture("regular_null")$generated$model
  testthat::expect_lt(max(abs(null$truth)), 1e-12)
})
